- name: Ensure app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    recurse: yes
    owner: deploy
    group: deploy

- name: Pull code from GitHub repo (branch + tag)
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: "{{ tag_name }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/deploy/.ssh/id_rsa"
  become: true
  become_user: deploy

- name: Run cap production deploy with BRANCH={{ tag_name }}
  shell: |
    BRANCH={{ tag_name }} cap production deploy
  args:
    chdir: "{{ app_dir }}"
  become: true
  become_user: deploy
  environment:
    RAILS_ENV: production
